# Generated by Django 5.0.7 on 2024-07-13 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('model', models.CharField(max_length=150, verbose_name='модель')),
                ('release_date', models.DateField(verbose_name='дата выпуска')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='SalesNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[(0, 'завод'), (1, 'розничная сеть'), (2, 'индивидуальный предприниматель')], max_length=100, verbose_name='уровень')),
                ('name', models.CharField(max_length=250, verbose_name='название')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('country', models.CharField(blank=True, max_length=150, null=True, verbose_name='страна')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='город')),
                ('street', models.CharField(blank=True, max_length=150, null=True, verbose_name='улица')),
                ('building', models.CharField(blank=True, max_length=15, null=True, verbose_name='номер дома')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='задолженность')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('product', models.ManyToManyField(to='onlineshop.product', verbose_name='продукты')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineshop.salesnetwork', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'звено',
                'verbose_name_plural': 'звенья',
            },
        ),
    ]
