# Generated by Django 5.0.7 on 2024-07-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0003_alter_salesnetwork_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesnetwork',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='onlineshop.product', verbose_name='продукты'),
        ),
    ]
